server:
  port: 8081
  servlet:
    context-path: /SpringBoot
height: top

person:
  name: zhansan${random.uuid}
  age : 19
  birth : 2020/04/05
  boss : false
  map : {k1: v1,k2: v2}
  lists :
    - apple
    - orange
  dog :
    name : 锄头${person.name}
    age  : 3